# Generated by Django 4.1.7 on 2023-05-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas'),
        ),
    ]
