# Generated by Django 4.1.7 on 2023-05-10 22:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetas', '0004_alter_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
